Attribute VB_Name = "EditableSystemArchitectureDiagram"
Option Explicit

' PowerPoint VBA module.
' ASCII source only. Chinese labels are generated by ChrW at runtime.
' Usage:
' 1. Open PowerPoint and press Alt+F11.
' 2. File -> Import File, import this .bas file.
' 3. Run CreateEditableSystemArchitectureDiagram.
'
' Every box, arrow and label is an editable PowerPoint shape.
' The arm photo is inserted as a normal picture object, so it can be moved,
' cropped, resized or replaced in PowerPoint.

Private Const FONT_NAME As String = "Microsoft YaHei"
Private Const ARM_PHOTO_PATH As String = "C:\Users\lin\xwechat_files\wxid_vdzq40bwc16322_6b2a\temp\RWTemp\2026-06\3bdb483720667eea1b423002b0abc872\59a4fae2a320b78dd3ff0ab67f212f19.jpg"

Public Sub CreateEditableSystemArchitectureDiagram()
    Dim pres As Presentation
    Dim sld As Slide
    Dim sw As Single
    Dim darkText As Long, muted As Long, bg As Long
    Dim cyan As Long, blue As Long, orange As Long, green As Long
    Dim red As Long, gray As Long, yellow As Long

    Set pres = ActivePresentation
    pres.PageSetup.SlideSize = ppSlideSizeOnScreen16x9
    sw = pres.PageSetup.SlideWidth

    Set sld = pres.Slides.Add(pres.Slides.Count + 1, ppLayoutBlank)

    bg = RGB(243, 246, 250)
    darkText = RGB(19, 32, 51)
    muted = RGB(96, 112, 134)
    cyan = RGB(23, 139, 149)
    blue = RGB(36, 107, 206)
    orange = RGB(217, 101, 40)
    green = RGB(22, 131, 74)
    red = RGB(204, 52, 52)
    gray = RGB(101, 115, 134)
    yellow = RGB(199, 139, 19)

    sld.Background.Fill.ForeColor.RGB = bg

    AddText sld, T("667A 80A4 5B9A 9776 7CFB 7EDF 603B 4F53 67B6 6784 56FE"), 38, 22, 560, 34, 25, darkText, True, ppAlignLeft
    AddText sld, T("5355 76EE 6444 50CF 5934 0020 002D 003E 0020 004A 0065 0074 0073 006F 006E 0020 004E 0061 006E 006F 0020 002D 003E 0020 0052 0041 0036 004D 0035 0020 002D 003E 0020 4E94 8F74 673A 68B0 81C2 0020 002F 0020 6307 793A 5149 0020 002F 0020 6025 505C 9650 4F4D 0020 002F 0020 65E5 5FD7 8BB0 5F55"), 39, 58, sw - 80, 18, 10.5, muted, False, ppAlignLeft

    AddStepCard sld, 38, 103, 155, 118, cyan, "CAM", "01 " & T("611F 77E5 8F93 5165"), T("5355 76EE 6444 50CF 5934"), T("91C7 96C6 9776 533A 56FE 50CF"), Array(T("76AE 80A4 533A 57DF 4E0E 9776 70B9 753B 9762"), T("8FDE 7EED 56FE 50CF 5E27 8F93 5165"), T("0055 0053 0042 0020 002F 0020 0043 0053 0049 0020 89C6 9891 6D41")), darkText, muted
    AddStepCard sld, 228, 103, 175, 118, blue, "AI", "02 " & T("8FB9 7F18 8BA1 7B97"), "Jetson Nano", T("89C6 89C9 8BC6 522B 4E0E 5750 6807 89E3 7B97"), Array(T("9776 70B9 8BC6 522B 0020 002F 0020 56FE 50CF 5904 7406"), T("50CF 7D20 5750 6807 5230 7A7A 95F4 5750 6807"), T("751F 6210 63A7 5236 7B56 7565")), darkText, muted
    AddStepCard sld, 445, 103, 175, 118, orange, "MCU", "03 " & T("5B9E 65F6 63A7 5236"), "RA6M5", T("8FD0 52A8 8F93 51FA 4E0E 5B89 5168 4E92 9501"), Array(T("4E32 53E3 901A 4FE1 4E0E 6307 4EE4 89E3 6790"), T("0050 0057 004D 0020 002F 0020 0047 0050 0049 004F 0020 5B9E 65F6 8F93 51FA"), T("6025 505C 9650 4F4D 72B6 6001 91C7 96C6")), darkText, muted

    AddArrow sld, 193, 162, 228, 162, blue, 3.6, False
    AddLineLabel sld, 199, 146, 41, 18, T("56FE 50CF 6D41"), blue
    AddArrow sld, 403, 162, 445, 162, blue, 3.6, False
    AddLineLabel sld, 397, 146, 78, 18, T("76EE 6807 5750 6807 0020 002F 0020 63A7 5236 6307 4EE4"), blue

    AddPhotoPanel sld, 662, 75, 258, 372, green, darkText, muted
    AddArrow sld, 620, 162, 662, 162, green, 4, False
    AddLineLabel sld, 612, 146, 55, 18, T("8FD0 52A8 63A7 5236"), green

    AddBoundaryBox sld, 38, 252, 155, 169, darkText, muted, cyan, blue, orange, red
    AddMiniCard sld, 228, 276, 180, 80, gray, "LOG", T("65E5 5FD7 8BB0 5F55"), Array(T("004A 0065 0074 0073 006F 006E 0020 4E0E 0020 0052 0041 0036 004D 0035 0020 8BB0 5F55 8FD0 884C 72B6 6001"), T("4FDD 5B58 6307 4EE4 3001 5F02 5E38 4E0E 8C03 8BD5 4FE1 606F")), darkText, muted
    AddMiniCard sld, 445, 276, 175, 80, yellow, "LED", T("6307 793A 5149"), Array(T("5DE5 4F5C 3001 5BF9 51C6 3001 544A 8B66 72B6 6001 63D0 793A"), T("7ED9 64CD 4F5C 8005 63D0 4F9B 53EF 89C6 53CD 9988")), darkText, muted
    AddMiniCard sld, 445, 382, 175, 80, red, "STOP", T("6025 505C 0020 002F 0020 9650 4F4D"), Array(T("6025 505C 6309 94AE 4E0E 884C 7A0B 9650 4F4D 8F93 5165"), T("5F02 5E38 65F6 8FDB 5165 5B89 5168 4E92 9501")), darkText, muted

    AddArrow sld, 533, 221, 533, 276, yellow, 3.3, False
    AddLineLabel sld, 502, 246, 58, 18, T("0049 002F 004F 0020 8F93 51FA"), yellow
    AddArrow sld, 445, 316, 408, 316, gray, 3.2, False
    AddLineLabel sld, 398, 300, 60, 18, T("72B6 6001 0020 002F 0020 5F02 5E38"), gray
    AddElbowArrow sld, 620, 422, 620, 332, red, 3.1, True
    AddLineLabel sld, 597, 367, 58, 18, T("5B89 5168 53CD 9988"), red

    AddSummary sld, 38, 478, 882, 44, darkText, muted, cyan, blue, orange
End Sub

Private Sub AddStepCard(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, _
                        ByVal accent As Long, ByVal badge As String, ByVal stepText As String, ByVal titleText As String, _
                        ByVal subText As String, ByVal bulletItems As Variant, ByVal textColor As Long, ByVal mutedColor As Long)
    AddCardBase sld, x, y, w, h, accent
    AddIconBadge sld, x + 17, y + 21, 36, accent, badge
    AddText sld, stepText, x + 62, y + 19, w - 74, 16, 9.5, accent, True, ppAlignLeft
    AddText sld, titleText, x + 62, y + 39, w - 74, 24, 15.5, textColor, True, ppAlignLeft
    AddText sld, subText, x + 62, y + 65, w - 74, 18, 9.8, mutedColor, False, ppAlignLeft
    AddBullets sld, x + 63, y + 89, w - 78, accent, mutedColor, bulletItems, 8.4
End Sub

Private Sub AddMiniCard(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, _
                        ByVal accent As Long, ByVal badge As String, ByVal titleText As String, ByVal lines As Variant, _
                        ByVal textColor As Long, ByVal mutedColor As Long)
    AddCardBase sld, x, y, w, h, accent
    AddIconBadge sld, x + 16, y + 18, 32, accent, badge
    AddText sld, titleText, x + 60, y + 18, w - 70, 19, 12.5, textColor, True, ppAlignLeft
    AddText sld, CStr(lines(0)), x + 60, y + 42, w - 68, 14, 8.3, mutedColor, False, ppAlignLeft
    AddText sld, CStr(lines(1)), x + 60, y + 57, w - 68, 14, 8.3, mutedColor, False, ppAlignLeft
End Sub

Private Sub AddBoundaryBox(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, _
                           ByVal textColor As Long, ByVal mutedColor As Long, ByVal cyan As Long, ByVal blue As Long, _
                           ByVal orange As Long, ByVal red As Long)
    Dim shp As Shape
    Set shp = AddRoundRect(sld, x, y, w, h, RGB(255, 255, 255), RGB(216, 224, 234), 1.2)
    AddText sld, T("6570 636E 4E0E 63A7 5236 8FB9 754C"), x + 13, y + 18, w - 26, 20, 12.2, textColor, True, ppAlignLeft
    AddLegendItem sld, x + 14, y + 56, cyan, T("6444 50CF 5934 53EA 8D1F 8D23 56FE 50CF 8F93 5165"), mutedColor
    AddLegendItem sld, x + 14, y + 84, blue, T("004A 0065 0074 0073 006F 006E 0020 004E 0061 006E 006F 0020 8D1F 8D23 8BA1 7B97 4E0E 51B3 7B56"), mutedColor
    AddLegendItem sld, x + 14, y + 112, orange, T("0052 0041 0036 004D 0035 0020 8D1F 8D23 6BEB 79D2 7EA7 5B9E 65F6 63A7 5236"), mutedColor
    AddLegendItem sld, x + 14, y + 140, red, T("6025 505C 9650 4F4D 76F4 63A5 53C2 4E0E 5B89 5168 4E92 9501"), mutedColor
End Sub

Private Sub AddPhotoPanel(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, _
                          ByVal accent As Long, ByVal textColor As Long, ByVal mutedColor As Long)
    Dim shp As Shape
    Dim pic As Shape
    Set shp = AddRoundRect(sld, x, y, w, h, RGB(255, 255, 255), RGB(216, 224, 234), 1.2)
    AddText sld, T("4E94 8F74 673A 68B0 81C2 5B9E 7269 6267 884C 7AEF"), x + 18, y + 18, w - 36, 24, 14.5, textColor, True, ppAlignLeft
    AddPill sld, x + 18, y + 52, 42, 17, T("771F 5B9E 786C 4EF6"), accent, RGB(255, 255, 255), 8
    AddText sld, T("673A 68B0 81C2 3001 8235 673A 3001 63A7 5236 677F 4E0E 7EBF 675F 96C6 6210"), x + 72, y + 54, w - 90, 14, 8, mutedColor, False, ppAlignLeft

    If Len(Dir$(ARM_PHOTO_PATH)) > 0 Then
        Set pic = sld.Shapes.AddPicture(ARM_PHOTO_PATH, msoFalse, msoTrue, x + 47, y + 96, -1, -1)
        FitShape pic, x + 47, y + 96, 165, 248
        pic.Line.Visible = msoTrue
        pic.Line.ForeColor.RGB = RGB(205, 216, 229)
        pic.Line.Weight = 0.8
    Else
        Set shp = AddRoundRect(sld, x + 47, y + 96, 165, 248, RGB(246, 247, 249), RGB(205, 216, 229), 1)
        AddText sld, T("56FE 7247 672A 627E 5230 FF1A 8BF7 66FF 6362 673A 68B0 81C2 7167 7247"), x + 58, y + 190, 143, 26, 9.5, mutedColor, False, ppAlignCenter
    End If

    Set shp = AddRoundRect(sld, x + 18, y + 335, w - 36, 23, RGB(243, 248, 245), RGB(183, 218, 197), 1)
    AddText sld, T("6267 884C 76EE 6807 FF1A 6839 636E 0020 0052 0041 0036 004D 0035 0020 5B9E 65F6 63A7 5236 8F93 51FA 5B8C 6210 9776 70B9 5BF9 51C6"), x + 26, y + 339, w - 52, 14, 7.8, accent, True, ppAlignCenter
End Sub

Private Sub AddSummary(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, _
                       ByVal textColor As Long, ByVal mutedColor As Long, ByVal cyan As Long, ByVal blue As Long, ByVal orange As Long)
    Dim shp As Shape
    Set shp = AddRoundRect(sld, x, y, w, h, RGB(255, 255, 255), RGB(216, 224, 234), 1.2)
    AddText sld, T("8BC4 5BA1 770B 56FE 7ED3 8BBA"), x + 14, y + 9, 120, 18, 11.5, textColor, True, ppAlignLeft
    AddNumberedItem sld, x + 14, y + 30, cyan, "1", T("5355 76EE 6444 50CF 5934 91C7 96C6 9776 533A 56FE 50CF"), mutedColor
    AddNumberedItem sld, x + 265, y + 30, blue, "2", T("004A 0065 0074 0073 006F 006E 0020 004E 0061 006E 006F 0020 5B8C 6210 89C6 89C9 8BC6 522B 3001 5750 6807 89E3 7B97 4E0E 7B56 7565 89C4 5212"), mutedColor
    AddNumberedItem sld, x + 535, y + 30, orange, "3", T("0052 0041 0036 004D 0035 0020 8D1F 8D23 5B9E 65F6 63A7 5236 3001 5B89 5168 4E92 9501 3001 6307 793A 8F93 51FA 4E0E 65E5 5FD7 8BB0 5F55"), mutedColor
End Sub

Private Sub AddCardBase(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, ByVal accent As Long)
    Dim shp As Shape
    Set shp = AddRoundRect(sld, x + 3, y + 4, w, h, RGB(222, 230, 240), RGB(222, 230, 240), 0)
    shp.ZOrder msoSendToBack
    Set shp = AddRoundRect(sld, x, y, w, h, RGB(255, 255, 255), RGB(216, 224, 234), 1.2)
    Set shp = sld.Shapes.AddShape(msoShapeRectangle, x, y, 5, h)
    shp.Fill.ForeColor.RGB = accent
    shp.Line.Visible = msoFalse
End Sub

Private Sub AddBullets(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal dotColor As Long, _
                       ByVal textColor As Long, ByVal bulletItems As Variant, ByVal fontSize As Single)
    Dim i As Long
    Dim yy As Single
    For i = LBound(bulletItems) To UBound(bulletItems)
        yy = y + (i - LBound(bulletItems)) * 15
        With sld.Shapes.AddShape(msoShapeOval, x, yy + 5, 4, 4)
            .Fill.ForeColor.RGB = dotColor
            .Line.Visible = msoFalse
        End With
        AddText sld, CStr(bulletItems(i)), x + 10, yy, w - 10, 12, fontSize, textColor, False, ppAlignLeft
    Next i
End Sub

Private Sub AddLegendItem(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal colorValue As Long, ByVal labelText As String, ByVal textColor As Long)
    Dim shp As Shape
    Set shp = AddRoundRect(sld, x, y + 4, 14, 5, colorValue, colorValue, 0)
    AddText sld, labelText, x + 24, y - 2, 112, 14, 8.3, textColor, False, ppAlignLeft
End Sub

Private Sub AddNumberedItem(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal colorValue As Long, ByVal numberText As String, ByVal labelText As String, ByVal textColor As Long)
    Dim shp As Shape
    Set shp = sld.Shapes.AddShape(msoShapeOval, x, y, 13, 13)
    shp.Fill.ForeColor.RGB = colorValue
    shp.Line.Visible = msoFalse
    SetShapeText shp, numberText, 7.5, RGB(255, 255, 255), True, ppAlignCenter
    AddText sld, labelText, x + 20, y - 2, 230, 16, 7.8, textColor, False, ppAlignLeft
End Sub

Private Sub AddIconBadge(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal d As Single, ByVal colorValue As Long, ByVal labelText As String)
    Dim shp As Shape
    Set shp = sld.Shapes.AddShape(msoShapeOval, x, y, d, d)
    shp.Fill.ForeColor.RGB = RGB(248, 251, 255)
    shp.Line.ForeColor.RGB = colorValue
    shp.Line.Weight = 1.5
    SetShapeText shp, labelText, 7.5, colorValue, True, ppAlignCenter
End Sub

Private Sub AddPill(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, ByVal labelText As String, _
                    ByVal fillColor As Long, ByVal textColor As Long, ByVal fontSize As Single)
    Dim shp As Shape
    Set shp = AddRoundRect(sld, x, y, w, h, fillColor, fillColor, 0)
    SetShapeText shp, labelText, fontSize, textColor, True, ppAlignCenter
End Sub

Private Sub AddLineLabel(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, ByVal labelText As String, ByVal colorValue As Long)
    Dim shp As Shape
    Set shp = AddRoundRect(sld, x, y, w, h, RGB(255, 255, 255), colorValue, 1)
    SetShapeText shp, labelText, 7.5, colorValue, False, ppAlignCenter
End Sub

Private Sub AddArrow(ByVal sld As Slide, ByVal x1 As Single, ByVal y1 As Single, ByVal x2 As Single, ByVal y2 As Single, _
                     ByVal colorValue As Long, ByVal weight As Single, ByVal dashed As Boolean)
    Dim shp As Shape
    Set shp = sld.Shapes.AddConnector(msoConnectorStraight, x1, y1, x2, y2)
    With shp.Line
        .ForeColor.RGB = colorValue
        .Weight = weight
        .EndArrowheadStyle = msoArrowheadTriangle
        If dashed Then .DashStyle = msoLineDash
    End With
End Sub

Private Sub AddElbowArrow(ByVal sld As Slide, ByVal x1 As Single, ByVal y1 As Single, ByVal x2 As Single, ByVal y2 As Single, _
                          ByVal colorValue As Long, ByVal weight As Single, ByVal dashed As Boolean)
    Dim shp As Shape
    Set shp = sld.Shapes.AddConnector(msoConnectorElbow, x1, y1, x2, y2)
    With shp.Line
        .ForeColor.RGB = colorValue
        .Weight = weight
        .EndArrowheadStyle = msoArrowheadTriangle
        If dashed Then .DashStyle = msoLineDash
    End With
End Sub

Private Function AddRoundRect(ByVal sld As Slide, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, _
                              ByVal fillColor As Long, ByVal lineColor As Long, ByVal lineWeight As Single) As Shape
    Set AddRoundRect = sld.Shapes.AddShape(msoShapeRoundedRectangle, x, y, w, h)
    With AddRoundRect
        .Fill.ForeColor.RGB = fillColor
        If lineWeight <= 0 Then
            .Line.Visible = msoFalse
        Else
            .Line.Visible = msoTrue
            .Line.ForeColor.RGB = lineColor
            .Line.Weight = lineWeight
        End If
    End With
End Function

Private Sub AddText(ByVal sld As Slide, ByVal textValue As String, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single, _
                    ByVal fontSize As Single, ByVal textColor As Long, ByVal isBold As Boolean, ByVal alignment As PpParagraphAlignment)
    Dim shp As Shape
    Set shp = sld.Shapes.AddTextbox(msoTextOrientationHorizontal, x, y, w, h)
    SetShapeText shp, textValue, fontSize, textColor, isBold, alignment
End Sub

Private Sub SetShapeText(ByVal shp As Shape, ByVal textValue As String, ByVal fontSize As Single, ByVal textColor As Long, _
                         ByVal isBold As Boolean, ByVal alignment As PpParagraphAlignment)
    With shp.TextFrame
        .MarginLeft = 1
        .MarginRight = 1
        .MarginTop = 1
        .MarginBottom = 1
        .VerticalAnchor = msoAnchorMiddle
        .WordWrap = msoTrue
        With .TextRange
            .Text = textValue
            .Font.Name = FONT_NAME
            .Font.Size = fontSize
            If isBold Then
                .Font.Bold = msoTrue
            Else
                .Font.Bold = msoFalse
            End If
            .Font.Color.RGB = textColor
            .ParagraphFormat.Alignment = alignment
        End With
    End With
End Sub

Private Sub FitShape(ByVal shp As Shape, ByVal x As Single, ByVal y As Single, ByVal w As Single, ByVal h As Single)
    Dim r As Single
    If shp.Width <= 0 Or shp.Height <= 0 Then Exit Sub
    r = w / shp.Width
    If h / shp.Height < r Then r = h / shp.Height
    shp.Width = shp.Width * r
    shp.Height = shp.Height * r
    shp.Left = x + (w - shp.Width) / 2
    shp.Top = y + (h - shp.Height) / 2
End Sub

Private Function T(ByVal codes As String) As String
    Dim parts() As String
    Dim i As Long
    Dim out As String
    codes = Trim$(codes)
    If Len(codes) = 0 Then
        T = ""
        Exit Function
    End If
    parts = Split(codes, " ")
    For i = LBound(parts) To UBound(parts)
        If Len(parts(i)) > 0 Then out = out & ChrW$(CLng("&H" & parts(i)))
    Next i
    T = out
End Function
